version: '3'

services: 
    web:
        build: .
        ports: 
            - 3000:3000
        depends_on:
            - mongo-service
    mongo-service:
        image: mongo
        ports: 
            - 3001:27017
